// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalRTaskBoard.Persistence;

namespace SignalRTaskBoard.Migrations
{
    [DbContext(typeof(TaskBoardContext))]
    [Migration("20181113003112_parent-taskboards")]
    partial class parenttaskboards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignalRTaskBoard.Models.TaskBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("TaskBoards");
                });

            modelBuilder.Entity("SignalRTaskBoard.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColumnId");

                    b.Property<string>("Content");

                    b.Property<float?>("EstimatedHours");

                    b.Property<float?>("HoursCompleted");

                    b.Property<float?>("HoursRemaining");

                    b.Property<int>("IndexInColumn");

                    b.Property<int>("TaskBoardId");

                    b.HasKey("Id");

                    b.HasIndex("TaskBoardId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("SignalRTaskBoard.Models.WorkItem", b =>
                {
                    b.HasOne("SignalRTaskBoard.Models.TaskBoard")
                        .WithMany("WorkItems")
                        .HasForeignKey("TaskBoardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
